# Config file for automatic testing at travis-ci.org

language: python

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy
  - pip install wheel six mock pytest pytest-pep8

# Run test
script:
  - py.test $PYTEST_ARGS brainstorm

matrix:
  include:
    - python: "2.7"
      env: PYTEST_ARGS=
    - python: "3.3"
      env: PYTEST_ARGS=
    - python: "3.4"
      env: PYTEST_ARGS=
    - python: "2.7"
      env: PYTEST_ARGS="--pep8 -m pep8"

branches:
  only:
    - master
    - /^release.*$/